"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Navbar } from "../../components/navbar";
import { useAuth } from "../../components/auth-provider";
import { api, errorMessage } from "../../lib/api";

export default function PublicarPage() {
  const { usuario, listo } = useAuth();
  const [form, setForm] = useState({titulo:"", direccion:"", ciudad:"", descripcion:"", imagen_url:"", precio_noche:"", capacidad:"", amenidades:""});
  const [error, setError] = useState(""); const [mensaje, setMensaje] = useState(""); const [enviando, setEnviando] = useState(false);
  const actualizar = (campo: keyof typeof form, valor: string) => setForm(actual => ({...actual, [campo]: valor}));
  async function enviar(event: FormEvent) { event.preventDefault(); if (!usuario?.es_anfitrion) return; setError(""); setEnviando(true); try { const propiedad = await api<{id:number}>("/propiedades", {method:"POST", body:JSON.stringify({...form, precio_noche:Number(form.precio_noche), capacidad:Number(form.capacidad), anfitrion_id:usuario.id})}); const nombres = form.amenidades.split(",").map(x=>x.trim()).filter(Boolean); if (nombres.length) { const disponibles = await api<{id:number;nombre:string}[]>("/amenidades"); const ids = disponibles.filter(a=>nombres.some(n=>n.toLowerCase()===a.nombre.toLowerCase())).map(a=>a.id); await api(`/propiedades/${propiedad.id}/amenidades`, {method:"PUT", body:JSON.stringify({amenidad_ids:ids})}); } setMensaje("Propiedad publicada correctamente."); setForm({titulo:"", direccion:"", ciudad:"", descripcion:"", imagen_url:"", precio_noche:"", capacidad:"", amenidades:""}); } catch (cause) { setError(errorMessage(cause)); } finally { setEnviando(false); } }
  return <main className="min-h-screen bg-slate-50"><Navbar/><section className="mx-auto max-w-3xl px-6 py-12">{!listo ? <p>Cargando sesión…</p> : !usuario ? <div className="rounded-3xl bg-white p-8 shadow"><h1 className="text-3xl font-bold">Iniciá sesión para publicar</h1><Link href="/registro" className="mt-5 inline-block rounded-xl bg-rose-600 px-5 py-3 font-bold text-white">Ingresar</Link></div> : !usuario.es_anfitrion ? <div className="rounded-3xl bg-white p-8 shadow"><h1 className="text-3xl font-bold">Tu cuenta no es anfitriona</h1><p className="mt-3 text-slate-700">Registrate como anfitrión para publicar propiedades.</p></div> : <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><h1 className="text-3xl font-bold text-slate-950">Publicar propiedad</h1><p className="mt-2 text-slate-700">Completá los datos para recibir reservas.</p><form onSubmit={enviar} className="mt-7 grid gap-4 sm:grid-cols-2"><Etiqueta nombre="Título"><input className="campo" required value={form.titulo} onChange={e=>actualizar("titulo",e.target.value)}/></Etiqueta><Etiqueta nombre="Ciudad"><input className="campo" required value={form.ciudad} onChange={e=>actualizar("ciudad",e.target.value)}/></Etiqueta><Etiqueta nombre="Dirección"><input className="campo" required value={form.direccion} onChange={e=>actualizar("direccion",e.target.value)}/></Etiqueta><Etiqueta nombre="Imagen URL"><input className="campo" type="url" value={form.imagen_url} onChange={e=>actualizar("imagen_url",e.target.value)}/></Etiqueta><Etiqueta nombre="Precio por noche"><input className="campo" type="number" min="1" required value={form.precio_noche} onChange={e=>actualizar("precio_noche",e.target.value)}/></Etiqueta><Etiqueta nombre="Capacidad"><input className="campo" type="number" min="1" required value={form.capacidad} onChange={e=>actualizar("capacidad",e.target.value)}/></Etiqueta><Etiqueta nombre="Amenidades (separadas por coma)"><input className="campo" value={form.amenidades} onChange={e=>actualizar("amenidades",e.target.value)} placeholder="wifi, pileta"/></Etiqueta><Etiqueta nombre="Descripción"><textarea className="campo min-h-24" value={form.descripcion} onChange={e=>actualizar("descripcion",e.target.value)}/></Etiqueta>{error && <p className="sm:col-span-2 rounded bg-red-100 p-3 text-red-800">{error}</p>}{mensaje && <p className="sm:col-span-2 rounded bg-green-100 p-3 text-green-800">{mensaje}</p>}<button disabled={enviando} className="sm:col-span-2 rounded-xl bg-rose-600 py-3 font-bold text-white hover:bg-rose-700 disabled:bg-rose-300">{enviando?"Publicando…":"Publicar propiedad"}</button></form></div>}</section></main>;
}
function Etiqueta({nombre, children}:{nombre:string;children:React.ReactNode}) { return <label className="block font-semibold text-slate-800">{nombre}<span className="mt-1 block">{children}</span></label>; }
